/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {

    public static void main(String[] args) {
        
        // Comentario
        /*
        Comentario
        de
        bloco
        */
        /**Comentario Documentacao */
        System.out.println("Ola mundo");
        System.out.println("Meu segundo comando de saida");
    }
}
