/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaEscolha;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int codigoDoProduto = 4;
        String nomeDoProduto = "";
        
        switch(codigoDoProduto) {
        
            case 1:
                nomeDoProduto = "bala";
                break;
                
            case 2:
                nomeDoProduto = "bombom";
                break;
                
            default:
                System.out.println("Nao encontrei o codigo do produto.");
                
        }
        
        System.out.println(nomeDoProduto);
    }
}
