/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaFor;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       for(int i = 0; i <= 10; i++){
           System.out.println(i);
       }
       
       int c = 0;
       for(; c <= 10; c++){
           System.out.println(i);
       }
    }
}
