/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VariaveisTIposOperadores;

public class App {
    public static void main(String[] args) {
        int idade = 29;
        float cotacaoDolar = 5.3f;
        double cotacaoEuro = 5.62d;
        char genero = 'M';
        byte pontos = 0;
        boolean estaCadastrado = false;
        String frase = "Bom dia, tudo bom com vc??";
        
    }
}
